From the previous pull request on contrib
https://github.com/yggdrasil-network/yggdrasil-go/pull/647

I also added a fix for the interface detection. The `$` in the egrep search makes it unusable when using the JSON format (will work in HJSON).. It would  return an empty string.

diff --git a/files/yggdrasil.in b/files/yggdrasil.in
--- a/files/yggdrasil.in
+++ b/files/yggdrasil.in
@@ -1,8 +1,15 @@
 #!/bin/sh
 #
+# Put the yggdrasil and yggdrasilctl binaries into /usr/local/bin
+# Then copy this script into /etc/rc.d/yggdrasil
+# Finally, run:
+#   1. chmod +x /etc/rc.d/yggdrasil /usr/local/bin/{yggdrasil,yggdrasilctl}
+#   2. echo "yggdrasil_enable=yes" >> /etc/rc.d
+#   3. service yggdrasil start
+#
 # PROVIDE: yggdrasil
 # REQUIRE: networking
-# KEYWORD: shutdown
+# KEYWORD:
 
 . /etc/rc.subr
 
@@ -10,60 +17,52 @@ name="yggdrasil"
 rcvar="yggdrasil_enable"
 
 start_cmd="${name}_start"
-start_precmd="${name}_prestart"
 stop_cmd="${name}_stop"
-stop_postcmd="${name}_poststop"
 
 pidfile="/var/run/yggdrasil/${name}.pid"
 command="/usr/sbin/daemon"
 command_args="-P ${pidfile} -r -f ${yggdrasil_command}"
 
-yggdrasil_prestart()
+yggdrasil_start()
 {
-	test ! -x %%PREFIX%%/bin/yggdrasil && (
-		logger -s -t yggdrasil "Warning: %%PREFIX%%/bin/yggdrasil is missing or not executable"
-		logger -s -t yggdrasil "Copy the yggdrasil binary into %%PREFIX%%/bin and then chmod +x %%PREFIX%%/bin/yggdrasil"
+	test ! -x /usr/local/bin/yggdrasil && (
+		logger -s -t yggdrasil "Warning: /usr/local/bin/yggdrasil is missing or not executable"
+		logger -s -t yggdrasil "Copy the yggdrasil binary into /usr/local/bin and then chmod +x /usr/local/bin/yggdrasil"
 		return 1
 	)
 
-	test ! -f %%PREFIX%%/etc/yggdrasil.conf && (
-		logger -s -t yggdrasil "Generating new configuration file into %%PREFIX%%/etc/yggdrasil.conf"
-		%%PREFIX%%/bin/yggdrasil -genconf > %%PREFIX%%/etc/yggdrasil.conf
+	test ! -f /usr/local/etc/yggdrasil.conf && (
+		logger -s -t yggdrasil "Generating new configuration file into /usr/local/etc/yggdrasil.conf"
+		/usr/local/bin/yggdrasil -genconf > /usr/local/etc/yggdrasil.conf
 	)
 
-	tap_path="$(cat %%PREFIX%%/etc/yggdrasil.conf | egrep -o '/dev/tap[0-9]{1,2}$')"
+	tap_path="$(cat /usr/local/etc/yggdrasil.conf | egrep -o '/dev/tap[0-9]{1,2}')"
 	tap_name="$(echo -n ${tap_path} | tr -d '/dev/')"
 
-	/sbin/ifconfig ${tap_name} >/dev/null 2>&1 || (
+	/sbin/ifconfig ${tap_name} >/dev/null 2>&1
+
+	if [ $? != 0 ]; then
 		logger -s -t yggdrasil "Creating ${tap_name} adapter"
 		/sbin/ifconfig ${tap_name} create || logger -s -t yggdrasil "Failed to create ${tap_name} adapter"
-	)
+	else 
+		logger -s -t yggdrasil "Destroying ${tap_name} adapter"
+		/sbin/ifconfig ${tap_name} destroy || logger -s -t yggdrasil "Failed to destroy ${tap_name} adapter"
 
-	mkdir -p /var/run/yggdrasil
-}
-
-yggdrasil_start()
-{
-	/sbin/ifconfig ${tap_name} >/dev/null 2>&1 || (
-		logger -s -t yggdrasil "Creating ${tap_name} adapter"
-		/sbin/ifconfig ${tap_name} create || logger -s -t yggdrasil "Failed to create ${tap_name} adapter"
-	)
+	test ! -d /var/run/yggdrasil && mkdir -p /var/run/yggdrasil
 
 	logger -s -t yggdrasil "Starting yggdrasil"
-	${command} ${command_args} %%PREFIX%%/bin/yggdrasil -useconffile %%PREFIX%%/etc/yggdrasil.conf \
+	${command} ${command_args} /usr/local/bin/yggdrasil -useconffile /usr/local/etc/yggdrasil.conf \
 		1>/var/log/yggdrasil.stdout.log \
 		2>/var/log/yggdrasil.stderr.log &
+	route -6 add 200::/7 -iface ${tap_name} > /dev/null 1>/dev/null 2>/dev/null &
 }
 
 yggdrasil_stop()
 {
 	logger -s -t yggdrasil "Stopping yggdrasil"
 	test -f /var/run/yggdrasil/${name}.pid && kill -TERM $(cat /var/run/yggdrasil/${name}.pid)
-}
 
-yggdrasil_poststop()
-{
-	tap_path="$(cat %%PREFIX%%/etc/yggdrasil.conf | grep /dev/tap | egrep -o '/dev/.*$')"
+	tap_path="$(cat /usr/local/etc/yggdrasil.conf | grep /dev/tap | egrep -o '/dev/.*$')"
         tap_name="$(echo -n ${tap_path} | tr -d '/dev/')"
 
 	/sbin/ifconfig ${tap_name} >/dev/null 2>&1 && (
